### ISSUE TITLE
Request to support filtering by content type

### ISSUE THREAD

**Issue by ImJohnMDaniel** [mfoulks3200/har-analyzer#1]
First off, I am really liking this plugin.  It really does help digest and analyze HAR files. Thanks for creating this !

A feature request please.  When working in the HAR Analyzer pane, would it be possible to add a small frame on the upper part of the left panel that would allow me to filter by specific types.  I am thinking specifically about that ability to filter in the browser's DevTools -> Network panel by type.  

Thanks for the help!

**Comment by kimmminjae** [comment]
A full text search on URI would be helpful too

**Comment by kbrannen-mn** [comment]
Or filter out GET or POST. Or filter out all images (even if I have to name the extensions), CSS, or JS files ... so we can see only the GET and POST.

**Comment by mfoulks3200** [comment]
I'll take a look at adding this soon, should be relatively straight forward. 😄

**Comment by ImJohnMDaniel** [comment]
G'day @mfoulks3200 -- I see that the August 30th release incorporated changes related to this feature request.  The addition of the "GET", "POST", "PUT" and other buttons as well as the full text search are very nice additions.

Am I missing how to filter by content type though?  I am not seeing it in the new search panel.  My ask was specifically the ability to filter on the "log" -> "entries" -> "_resourceType" value in the HAR file.  Is it still possible to get this as a feature if it is not already there?

Just let me know when you can.  The work is very much appreciated!  I use this plugin periodically -- mostly to track through SAML SSO exchanges.   When I do use it though, it is VERY HELPFUL!!!

**Comment by mfoulks3200** [comment]
Gotcha, I'll re-open this issue for now then. Thanks for the kind words 😄

**Comment by ImJohnMDaniel** [comment]
G'day @mfoulks3200  -- Just took a look at the 10/2/2022 version and I love the new filtering feature.  Exactly what I was looking for.  Thank you so much sir!  Cheers!
