### ISSUE TITLE
need better instructions

### ISSUE THREAD

**Issue by kbrannen-mn** [mfoulks3200/har-analyzer#2]
The very minimal docs say: Run the **Analyze** command while viewing a har file to open the analyzer.

What does that mean exactly?

Right clicking the har file and choosing "Open with..." and entering "Analyze" doesn't work. Going to the Terminal in the file and typing "Analyze" doesn't work either. I've even restarted VScode to see if anything new appears, it doesn't. I can't tell what the video is doing other then trying to show the extension gives tabs to show data. All I see is the JSON of the file, not an analyzer.

**Comment by laurencee** [comment]
I agree that the instruction should be a little more specific.

It's referring to bringing up [Command Pallette](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_command-palette) (ctrl+shift+p) and running `Har Analyzer: Analyze`.

**Comment by kbrannen-mn** [comment]
Thanks! That helps and makes it work. :)

**Comment by mfoulks3200** [comment]
Feel free to submit a PR if you'd like to improve the instructions, but I think given the ecosystem of VS Code it's not necessary to explain the command palette.

**Comment by kbrannen-mn** [comment]
I can't push a branch up, so here's the diff for you to apply since it's only a 1 line change. HTH.

diff --git a/README.md b/README.md
index 08a98f1..a0e81ae 100644
--- a/README.md
+++ b/README.md
@@ -1,5 +1,5 @@
-A first-class HAR file viewer for VS Code. Run the `Analyze` command while viewing a har file to open the analyzer.
+A first-class HAR file viewer for VS Code. To run, while viewing a har file, open the Command Palette (Cntl-Shft-P) and choose "Har Analyzer: Analyze".

 ![Demo GIF](demo.gif)

**Comment by kbrannen-mn** [comment]
> Feel free to submit a PR if you'd like to improve the instructions, but I think given the ecosystem of VS Code it's not necessary to explain the command palette.

FWIW, I think the command palette is only obvious to you because you've been using it. I've been using VScode for the last 3 months and didn't even know the command palette existed until now. So newer users do need the few extra words to know how to run it.

**Comment by mfoulks3200** [comment]
Fair enough. Repository access is limited to myself only. To contribute, you must:

- Fork (copy) the repo to your account.
- Make the change in a commit.
- Push it back up to your repo.
- Create a pull request from the main branch on your fork to the main branch on this repo.

This is a fairly standard process, but if you're new to git, welcome! Doing things this way helps with permissions issues, allows for a formal code review process, and general organization.

When you've created the PR, just tag this issue in the description and I'll approve it.

If you make more changes in the future, you can keep working on your repo and create another pull request when you're ready. Thanks for contributing! 😄

**Comment by kbrannen-mn** [comment]
For a change this small, sorry, the diff will have to do. If you don't wish to do it, so be it.
I'm well versed in git, but the "github process" is more complicated than I care for -- especially for a 1 time small change. I know, not your fault as you didn't set it up. OTOH, I wonder how much other "help" is "lost" because of dislike of the process. (shrug)

**Comment by mfoulks3200** [comment]
Not quite sure what you mean, the process takes under 2-ish minutes, and can be done entirely from the website. I don't want to turn away contributors if I can help it, but maintaining this process helps make sure everything can be reviewed and cataloged easily.

All you have to do is click fork, create, readme.md, edit, make your change, commit, then create pull request.

I'll go ahead and close this issue out for the moment if you'd prefer not to create a PR, but I encourage you to try the process if you're able, it's quite easy once you've done it once, and it makes contributing to projects a breeze.

Thanks!
