### ISSUE TITLE
No POST data/params

### ISSUE THREAD

**Issue by kbrannen-mn** [mfoulks3200/har-analyzer#3]
When I go to an entry that is correctly marked POST, there is nothing showing the POST params, or what was sent in the post. I still have to bring the har file up in an editor to see that, so the tool really should show this data.

Thanks!

**Comment by kbrannen-mn** [comment]
I notice that your "media/example.har" file (for testing?) doesn't have a POST entry in it. Perhaps add a POST to it as well to ensure it comes out right in testing.

**Comment by mfoulks3200** [comment]
I'll look into the post data not showing up, as for the HAR file- Feel free to PR in a new one.
